[package]
name = "simple_proxy"
version = "0.1.0"
authors = ["karl.runge <karl.runge@defendtex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap    = "~2.33"
mavlink = "0.8.6"